/* eslint-disable */
/**
 * This file is auto-generated by `npm run generate:client`.
 * Do not edit manually.
 */

import createClient, { type ClientOptions } from "openapi-fetch";

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health-check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns the basic status of the web application.
     */
    get: {
      parameters: {
        query?: {
          /** @description Set to true to include a timestamp in the response. */
          includeTimestamp?: "true" | "false";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The application is healthy. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthCheckResponse"];
          };
        };
        /** @description The request query parameters were invalid. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthCheckValidationErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/profiles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get profile
     * @description Returns a profile by ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The profile ID. */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The profile was found. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProfileResponse"];
          };
        };
        /** @description The route parameters were invalid. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProfileValidationErrorResponse"];
          };
        };
        /** @description The request was unauthenticated. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProfileUnauthorizedResponse"];
          };
        };
        /** @description The authenticated user cannot access this profile. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProfileForbiddenResponse"];
          };
        };
        /** @description The profile was not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetProfileNotFoundResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthCheckResponse: {
      /**
       * @example ok
       * @enum {string}
       */
      status: "ok";
      /**
       * @example web
       * @enum {string}
       */
      service: "web";
      /**
       * Format: date-time
       * @example 2026-06-19T14:00:00.000Z
       */
      timestamp?: string;
    };
    HealthCheckValidationErrorResponse: {
      /** @example Invalid query parameters. */
      message: string;
      /**
       * @example [
       *       "includeTimestamp: Invalid option: expected one of \"true\"|\"false\""
       *     ]
       */
      issues: string[];
    };
    GetProfileResponse: {
      /**
       * Format: uuid
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
    };
    GetProfileValidationErrorResponse: {
      /** @example Invalid route parameters. */
      message: string;
      /**
       * @example [
       *       "id: Invalid UUID"
       *     ]
       */
      issues: string[];
    };
    GetProfileUnauthorizedResponse: {
      /** @example Authentication required. */
      message: string;
    };
    GetProfileForbiddenResponse: {
      /** @example You can only access your own profile. */
      message: string;
    };
    GetProfileNotFoundResponse: {
      /** @example Profile not found. */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type WebClient = ReturnType<typeof createWebClient>;
export type WebClientOptions = ClientOptions;

export function createWebClient(options: ClientOptions = {}) {
  return createClient<paths>(options);
}
