import { execFileSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import prettier from "prettier";
import { fileURLToPath } from "node:url";
import { openApiDocument } from "../../web/src/app/features/openapi/openapi-document";

const currentFilePath = fileURLToPath(import.meta.url);
const mobileToolsDir = path.dirname(currentFilePath);
const mobileAppRoot = path.resolve(mobileToolsDir, "..");
const repositoryRoot = path.resolve(mobileAppRoot, "..", "..");
const outputPath = path.join(mobileAppRoot, "src", "lib", "web-client.ts");

function getOpenApiTypescriptCliPath() {
  return path.join(
    repositoryRoot,
    "node_modules",
    "openapi-typescript",
    "bin",
    "cli.js",
  );
}

async function generateClient() {
  const tempDirectoryPath = await mkdtemp(
    path.join(os.tmpdir(), "meal-os-openapi-"),
  );
  const schemaPath = path.join(tempDirectoryPath, "openapi.json");

  try {
    await writeFile(schemaPath, JSON.stringify(openApiDocument, null, 2));

    const generatedTypes = execFileSync(
      process.execPath,
      [getOpenApiTypescriptCliPath(), schemaPath],
      {
        cwd: repositoryRoot,
        encoding: "utf8",
      },
    ).trim();

    const generatedSource = `/**
 * This file is auto-generated by \`npm run generate:client\`.
 * Do not edit manually.
 */

import createClient, { type ClientOptions } from "openapi-fetch";

${generatedTypes}

export type WebClient = ReturnType<typeof createWebClient>;
export type WebClientOptions = ClientOptions;

export function createWebClient(options: ClientOptions = {}) {
  return createClient<paths>(options);
}
`;

    const formattedSource = await prettier.format(generatedSource, {
      parser: "typescript",
    });

    await writeFile(outputPath, formattedSource);
  } finally {
    await rm(tempDirectoryPath, { recursive: true, force: true });
  }
}

generateClient().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
