import type { IngredientCategoryName } from "./ingredient-categories.seed.js";
import {
  defineSeed,
  getRequiredValue,
  longRunningTransactionOptions,
  toNameIdMap,
} from "./helpers.js";
import type { UnitName } from "./units.seed.js";

type IngredientSeed = {
  name: string;
  category: IngredientCategoryName;
  defaultUnit: UnitName;
};

const withIngredients = (
  category: IngredientCategoryName,
  defaultUnit: UnitName,
  names: readonly string[],
): IngredientSeed[] =>
  names.map((name) => ({
    name,
    category,
    defaultUnit,
  }));

export const ingredients = [
  ...withIngredients("Produce", "each", [
    "Apple",
    "Banana",
    "Orange",
    "Lemon",
    "Lime",
    "Avocado",
    "Tomato",
    "Roma Tomato",
    "Cherry Tomato",
    "Cucumber",
    "Zucchini",
    "Yellow Squash",
    "Eggplant",
    "Bell Pepper",
    "Red Bell Pepper",
    "Green Bell Pepper",
    "Yellow Bell Pepper",
    "Yellow Onion",
    "Red Onion",
    "White Onion",
    "Sweet Onion",
    "Shallot",
    "Garlic",
    "Ginger",
    "Russet Potato",
    "Yukon Gold Potato",
    "Red Potato",
    "Sweet Potato",
    "Carrot",
    "Celery",
    "Broccoli",
    "Cauliflower",
    "Cabbage",
    "Red Cabbage",
    "Corn",
    "Jalapeno",
    "Serrano Pepper",
    "Poblano Pepper",
    "Portobello Mushroom",
    "Leek",
    "Bok Choy",
    "Butternut Squash",
    "Spaghetti Squash",
    "Acorn Squash",
    "Pumpkin",
    "Turnip",
    "Parsnip",
    "Pineapple",
    "Mango",
    "Peach",
    "Pear",
    "Kiwi",
    "Cantaloupe",
    "Watermelon",
    "Romaine Lettuce",
    "Iceberg Lettuce",
    "Butter Lettuce",
  ]),
  ...withIngredients("Produce", "package", [
    "White Mushroom",
    "Baby Bella Mushroom",
    "Baby Spinach",
    "Arugula",
    "Mixed Greens",
    "Coleslaw Mix",
    "Blueberries",
    "Strawberries",
    "Raspberries",
    "Blackberries",
  ]),
  ...withIngredients("Produce", "bag", [
    "Grapes",
  ]),
  ...withIngredients("Produce", "bunch", [
    "Radish",
    "Beets",
    "Cilantro",
    "Parsley",
    "Dill",
    "Green Onion",
    "Asparagus",
    "Kale",
    "Swiss Chard",
    "Fresh Basil",
    "Fresh Mint",
    "Fresh Rosemary",
    "Fresh Thyme",
  ]),
  ...withIngredients("Produce", "pound", [
    "Green Beans",
    "Snow Peas",
    "Sugar Snap Peas",
    "Okra",
    "Brussels Sprouts",
  ]),
  ...withIngredients("Meat & Seafood", "pound", [
    "Ground Beef",
    "Beef Stew Meat",
    "Beef Chuck Roast",
    "Beef Sirloin",
    "Flank Steak",
    "Ribeye Steak",
    "Pork Chops",
    "Pork Tenderloin",
    "Pork Shoulder",
    "Ground Pork",
    "Bacon",
    "Breakfast Sausage",
    "Italian Sausage",
    "Chorizo",
    "Chicken Breast",
    "Chicken Thigh",
    "Chicken Wings",
    "Whole Chicken",
    "Ground Turkey",
    "Turkey Breast",
    "Ground Chicken",
    "Salmon Fillet",
    "Cod Fillet",
    "Tilapia Fillet",
    "Shrimp",
    "Scallops",
    "Tuna Steak",
    "Crab Meat",
  ]),
  ...withIngredients("Meat & Seafood", "package", [
    "Deli Ham",
    "Deli Turkey",
    "Pepperoni",
  ]),
  ...withIngredients("Dairy & Eggs", "dozen", [
    "Eggs",
  ]),
  ...withIngredients("Dairy & Eggs", "carton", [
    "Egg Whites",
    "Milk",
    "Heavy Cream",
    "Half and Half",
    "Buttermilk",
    "Almond Milk",
    "Oat Milk",
  ]),
  ...withIngredients("Dairy & Eggs", "container", [
    "Greek Yogurt",
    "Plain Yogurt",
    "Sour Cream",
    "Cottage Cheese",
    "Feta Cheese",
    "Goat Cheese",
    "Ricotta Cheese",
  ]),
  ...withIngredients("Dairy & Eggs", "block", [
    "Cream Cheese",
  ]),
  ...withIngredients("Dairy & Eggs", "stick", [
    "Butter",
  ]),
  ...withIngredients("Dairy & Eggs", "package", [
    "Cheddar Cheese",
    "Mozzarella Cheese",
    "Monterey Jack Cheese",
    "Parmesan Cheese",
    "Swiss Cheese",
    "String Cheese",
    "Shredded Cheddar Cheese",
    "Shredded Mozzarella Cheese",
  ]),
  ...withIngredients("Bakery", "loaf", [
    "Sandwich Bread",
    "Sourdough Bread",
    "French Bread",
    "Italian Bread",
    "Whole Wheat Bread",
  ]),
  ...withIngredients("Bakery", "package", [
    "Hamburger Buns",
    "Hot Dog Buns",
    "Flour Tortillas",
    "Corn Tortillas",
    "Pita Bread",
    "Naan",
    "English Muffins",
    "Bagels",
    "Croissants",
    "Pizza Dough",
    "Pie Crust",
  ]),
  ...withIngredients("Bakery", "bag", [
    "Bread Crumbs",
    "Croutons",
  ]),
  ...withIngredients("Grains & Pasta", "bag", [
    "White Rice",
    "Brown Rice",
    "Jasmine Rice",
    "Basmati Rice",
    "Arborio Rice",
    "Quinoa",
    "Rolled Oats",
    "Steel Cut Oats",
    "Farro",
    "Pearled Barley",
    "Polenta",
    "Cornmeal",
    "Dry Lentils",
    "Dry Black Beans",
    "Dry Pinto Beans",
    "Dry Chickpeas",
  ]),
  ...withIngredients("Grains & Pasta", "box", [
    "Couscous",
    "Spaghetti",
    "Penne",
    "Fettuccine",
    "Macaroni",
    "Rotini",
    "Linguine",
    "Lasagna Noodles",
    "Orzo",
  ]),
  ...withIngredients("Grains & Pasta", "package", [
    "Ramen Noodles",
    "Rice Noodles",
  ]),
  ...withIngredients("Grains & Pasta", "bag", [
    "Egg Noodles",
  ]),
  ...withIngredients("Canned Goods", "can", [
    "Diced Tomatoes",
    "Crushed Tomatoes",
    "Tomato Sauce",
    "Tomato Paste",
    "Whole Peeled Tomatoes",
    "Fire-Roasted Tomatoes",
    "Green Chiles",
    "Black Beans",
    "Pinto Beans",
    "Cannellini Beans",
    "Chickpeas",
    "Kidney Beans",
    "Corn Kernels",
    "Coconut Milk",
    "Cream of Mushroom Soup",
    "Cream of Chicken Soup",
    "Pumpkin Puree",
    "Evaporated Milk",
    "Sweetened Condensed Milk",
    "Canned Tuna",
    "Canned Salmon",
    "Artichoke Hearts",
    "Enchilada Sauce",
    "Black Olives",
    "Sardines",
  ]),
  ...withIngredients("Canned Goods", "carton", [
    "Chicken Broth",
    "Vegetable Broth",
    "Beef Broth",
    "Chicken Stock",
    "Vegetable Stock",
    "Beef Stock",
  ]),
  ...withIngredients("Baking", "bag", [
    "All-Purpose Flour",
    "Bread Flour",
    "Whole Wheat Flour",
    "Almond Flour",
    "Granulated Sugar",
    "Brown Sugar",
    "Powdered Sugar",
    "Sweetened Coconut Flakes",
    "Walnuts",
    "Pecans",
  ]),
  ...withIngredients("Baking", "box", [
    "Baking Soda",
    "Cornstarch",
    "Baking Mix",
  ]),
  ...withIngredients("Baking", "container", [
    "Baking Powder",
    "Cocoa Powder",
  ]),
  ...withIngredients("Baking", "package", [
    "Chocolate Chips",
    "White Chocolate Chips",
    "Active Dry Yeast",
    "Instant Yeast",
  ]),
  ...withIngredients("Baking", "bottle", [
    "Vanilla Extract",
    "Almond Extract",
  ]),
  ...withIngredients("Baking", "jar", [
    "Sprinkles",
  ]),
  ...withIngredients("Oils, Vinegars & Condiments", "bottle", [
    "Olive Oil",
    "Vegetable Oil",
    "Canola Oil",
    "Avocado Oil",
    "Sesame Oil",
    "Apple Cider Vinegar",
    "White Vinegar",
    "Red Wine Vinegar",
    "Balsamic Vinegar",
    "Soy Sauce",
    "Tamari",
    "Worcestershire Sauce",
    "Hot Sauce",
    "Fish Sauce",
    "Barbecue Sauce",
    "Ketchup",
    "Yellow Mustard",
    "Ranch Dressing",
    "Italian Dressing",
    "Caesar Dressing",
    "Buffalo Sauce",
    "Teriyaki Sauce",
    "Hoisin Sauce",
    "Oyster Sauce",
    "Sriracha",
    "Maple Syrup",
    "Honey",
    "Molasses",
  ]),
  ...withIngredients("Oils, Vinegars & Condiments", "jar", [
    "Dijon Mustard",
    "Mayonnaise",
    "Peanut Butter",
    "Jam",
    "Grape Jelly",
    "Salsa",
    "Tahini",
    "Relish",
    "Pesto",
    "Marinara Sauce",
  ]),
  ...withIngredients("Herbs & Spices", "jar", [
    "Kosher Salt",
    "Sea Salt",
    "Black Pepper",
    "Garlic Powder",
    "Onion Powder",
    "Paprika",
    "Smoked Paprika",
    "Cayenne Pepper",
    "Crushed Red Pepper",
    "Chili Powder",
    "Ground Cumin",
    "Cumin Seeds",
    "Ground Coriander",
    "Coriander Seeds",
    "Dried Oregano",
    "Dried Basil",
    "Dried Thyme",
    "Dried Rosemary",
    "Dried Parsley",
    "Bay Leaves",
    "Italian Seasoning",
    "Poultry Seasoning",
    "Curry Powder",
    "Garam Masala",
    "Ground Turmeric",
    "Ground Ginger",
    "Ground Cinnamon",
    "Ground Nutmeg",
    "Ground Allspice",
    "Ground Cloves",
    "Ground Cardamom",
    "Mustard Powder",
    "Celery Seed",
    "Sesame Seeds",
    "Poppy Seeds",
    "Fennel Seed",
    "Taco Seasoning",
    "Cajun Seasoning",
    "Old Bay Seasoning",
    "Steak Seasoning",
    "Everything Bagel Seasoning",
    "Lemon Pepper",
    "Seasoned Salt",
    "Dried Sage",
    "Herbes de Provence",
    "Pumpkin Pie Spice",
    "Chinese Five Spice",
  ]),
  ...withIngredients("Frozen Foods", "bag", [
    "Frozen Peas",
    "Frozen Corn",
    "Frozen Broccoli",
    "Frozen Spinach",
    "Frozen Mixed Vegetables",
    "Frozen Hash Browns",
    "Frozen French Fries",
    "Frozen Berries",
    "Frozen Mango",
    "Frozen Edamame",
    "Frozen Ravioli",
    "Frozen Meatballs",
    "Frozen Shrimp",
  ]),
  ...withIngredients("Frozen Foods", "box", [
    "Frozen Pizza",
    "Frozen Waffles",
  ]),
  ...withIngredients("Frozen Foods", "container", [
    "Ice Cream",
  ]),
  ...withIngredients("Snacks & Beverages", "bag", [
    "Potato Chips",
    "Tortilla Chips",
    "Pretzels",
    "Popcorn Kernels",
    "Trail Mix",
    "Granola",
    "Coffee Beans",
    "Ground Coffee",
    "Dried Fruit",
  ]),
  ...withIngredients("Snacks & Beverages", "box", [
    "Crackers",
    "Cereal",
    "Granola Bars",
    "Tea Bags",
  ]),
  ...withIngredients("Snacks & Beverages", "package", [
    "Cookies",
    "Rice Cakes",
  ]),
  ...withIngredients("Snacks & Beverages", "bottle", [
    "Sparkling Water",
    "Sports Drink",
    "Soda",
  ]),
  ...withIngredients("Snacks & Beverages", "carton", [
    "Orange Juice",
    "Apple Juice",
    "Coconut Water",
    "Lemonade",
  ]),
] satisfies readonly IngredientSeed[];

export type IngredientName = (typeof ingredients)[number]["name"];

export const seedIngredients = defineSeed("ingredients", async (prisma) =>
  prisma.$transaction(
    async (tx) => {
      const [categories, units] = await Promise.all([
        tx.ingredientCategory.findMany({
          select: {
            id: true,
            name: true,
          },
        }),
        tx.unit.findMany({
          select: {
            id: true,
            name: true,
          },
        }),
      ]);

      const categoryIds = toNameIdMap(categories);
      const unitIds = toNameIdMap(units);

      for (const ingredient of ingredients) {
        const categoryId = getRequiredValue(
          categoryIds,
          ingredient.category,
          "Ingredient category",
        );
        const defaultUnitId = getRequiredValue(
          unitIds,
          ingredient.defaultUnit,
          "Unit",
        );

        await tx.ingredient.upsert({
          where: {
            name: ingredient.name,
          },
          update: {
            categoryId,
            defaultUnitId,
          },
          create: {
            name: ingredient.name,
            categoryId,
            defaultUnitId,
          },
        });
      }

      return ingredients.length;
    },
    longRunningTransactionOptions,
  ),
);
